baseURL = "https://drehwurm.band/"
languageCode = "de-de"
title = "Drehwurm"
theme = "hugo-scroll"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Eine Balfolk Band aus Drehsden"
    favicon = "img/favicon.jpg"
[Author]
    name = "Drehwurm"
    email = "info@drehwurm.band"
