baseURL = "https://drehwurm.band/"
languageCode = "de-de"
title = "Drehwurm"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Die Webseite für die Balfolk Band Drehwurm"

[Author]
    name = "Drehwurm"
    email = "info@drehwurm.band"
